### ISSUE TITLE
Thrustmaster T.Flight Hotas 4 not recognized

### ISSUE THREAD

**Issue by bohni** [arithex/ThrottleOverlay#1]
Hi,

I can't get your cool tool running with T.Flight Hotas 4
![grafik](https://user-images.githubusercontent.com/1252254/154807558-db15b43f-bb84-4208-af0d-f48796a805a3.png)
<add key="ThrottleAxis" value="B67C,044F,50"/>

Logitach Extreme 3D Pro works correct with
<add key="ThrottleAxis" value="C215,046D,54"/>

**Comment by arithex** [comment]
What is the name/id of the axis?  (Typically 'Z' or 'Slider0' or 'Slider1')

I really need to build in some sort of auto-recognizer feature..

**Comment by bohni** [comment]
It's the Z-Axis
![image](https://user-images.githubusercontent.com/1252254/154815334-64256cc3-a01f-4ea0-8906-3ec6ac335dc0.png)
I tried "48" through "56" - none worked

https://github.com/arithex/ThrottleOverlay/blob/e2581cf8465bad5bf600c6197627650df076472f/src/Win32_RawInput.cs#L50
Kind of logging (Console, File) would be cool to look for the values of these four ids...

**Comment by bohni** [comment]
Update:
I just tried again and 48/49/50/53/55 showed some reaction -unfortunately not the desired one:
throttle indicator switches instant from center to bottom, then nothing happens anymore.

48 (true and false): roll fully left (X-axis) (with fully right the indicator stays centered)
49 - same for y-axis (fully up)
50 - same for Z-axis (full throttle)
53 - same for rZ (rudder fully left, twisting handle)
55 - same for Slider1 (rudder fully left, rocking button) - see manual at https://support.thrustmaster.com/en/product/tflighthotas4-en/

Update 2:
Looked at the values shown in "VKB joytester" and the value from the stated condition is always "0" when the indicator switches to bottom
Value range from all axis is 0 to 65535
![image](https://user-images.githubusercontent.com/1252254/154816697-5a9fe63f-53d8-4b53-91e1-99c21297cc77.png)

**Comment by arithex** [comment]
Weird.  Any special configuration with Thrustmaster Target?   The device works ok, in games?

I'll make a special build with some logging .. but I expect it will show identical to VKB JoyTester.

**Comment by bohni** [comment]
The Device works in games - and VKB JoyTester reads the Axis correctly and outputs nice curves

Since the throttle display changes when the axis' are fully at the endpoint, the device should correctly be recognized by your code.
The question is, why the values aren't read correctly...

**Comment by arithex** [comment]
Thanks for confirming -- unfortunately I think you've found a pretty fundamental bug in my code, in its handling of multiple devices.  Not sure how it passed testing..   I'm working on a fix.

**Comment by arithex** [comment]
https://github.com/arithex/ThrottleOverlay/releases/tag/v1.0.2022.220-debug

Let me know if this works better.  If any exceptions or debug-assertions appear, in the console window, paste them here...   I'll continue to test this, in parallel, with several devices..   and I'll improve the error-logging, so future releases can run without the console window.

Thanks again for finding this bug!

**Comment by bohni** [comment]
Thanks for the debug version. Sadly, I got following output just by pressing a button once... This is of course repeating when moving any axis...

```
======= EXCEPTION =======
System.ArgumentOutOfRangeException: Das angegebene Argument liegt außerhalb des gültigen Wertebereichs.
Parametername: Encountered HID axis value outside min/max range.
   bei Win32.RawInput.DecodeJoystickAxisEvent(IntPtr hRawInput, UInt16 vendorId, UInt16 productId, UInt16 axisId, JoystickAxisHandler onJoystickAxis) in C:\1\zzz\ThrottleOverlay\src\Win32_RawInput.cs:Zeile 99.
   bei ThrottleOverlay.RawInputJoystickHandler.ProcessRawInputMessage(IntPtr hRawInput) in C:\1\zzz\ThrottleOverlay\src\RawInputJoystickHandler.cs:Zeile 52.
   bei ThrottleOverlay.App._WndProcImpl(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in C:\1\zzz\ThrottleOverlay\src\App.xaml.cs:Zeile 63.
   bei ThrottleOverlay.App._WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in C:\1\zzz\ThrottleOverlay\src\App.xaml.cs:Zeile 37.
======= EXCEPTION =======
System.ArgumentOutOfRangeException: Das angegebene Argument liegt außerhalb des gültigen Wertebereichs.
Parametername: Encountered HID axis value outside min/max range.
   bei Win32.RawInput.DecodeJoystickAxisEvent(IntPtr hRawInput, UInt16 vendorId, UInt16 productId, UInt16 axisId, JoystickAxisHandler onJoystickAxis) in C:\1\zzz\ThrottleOverlay\src\Win32_RawInput.cs:Zeile 99.
   bei ThrottleOverlay.RawInputJoystickHandler.ProcessRawInputMessage(IntPtr hRawInput) in C:\1\zzz\ThrottleOverlay\src\RawInputJoystickHandler.cs:Zeile 52.
   bei ThrottleOverlay.App._WndProcImpl(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in C:\1\zzz\ThrottleOverlay\src\App.xaml.cs:Zeile 63.
   bei ThrottleOverlay.App._WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in C:\1\zzz\ThrottleOverlay\src\App.xaml.cs:Zeile 37.
```

**Comment by bohni** [comment]
I finally decided to install VS Community Edition an debugged a little bit.
I'm a Java dev and have no idea of C++/Win32 and USB... But I did temporarly some  C#  at work...

I found that both 
```
uint rawMin = (uint)(axisValueCaps.physicalMin);
uint rawMax = (uint)(axisValueCaps.physicalMax);
```
values are 0

`rawValue `changes  on Throttle Axis (Z, 50) from 255 to 0

Let me know, how I can further help you track down that nasty little bug...

Update: Same on X-Axis, 48 (min, max 0, but rawValue 0 to 1024)

**Comment by arithex** [comment]
(I also see the exception when pressing a button .. that's harmless noise, I'll clean that up.)

The physicalMax reporting as 0 is more concerning.  Not sure what could cause that.. I haven't seen that in my testing.  I'll prep another build, with more diagnostic output.

**Comment by bohni** [comment]
Hi, as I wrote, physicalMin/physicalMax always return 0.
But logicalMin/logicalMax report values, that lead to a working UI.

**Comment by arithex** [comment]
Thanks -- that's what I needed to learn.  I'd been working on diagnostic code to log all of the axes caps.   But a patch to use logicalMin/Max should be quick and easy.

**Comment by arithex** [comment]
I don't have a T.Flight Hotas 4 to test, but hopefully this works now.
https://github.com/arithex/ThrottleOverlay/releases/tag/v1.0.2022.311

**Comment by bohni** [comment]
Thanks.

It works with my Hotas 4.
